#!/usr/bin/env python3
"""Build the Couchbase API tube-style map.

Generated by batch generator. 
"""

import sys
from pathlib import Path

sys.path.insert(0, "/Users/kinlane/GitHub/all/.claude/skills")
from _subway_engine import build_subway  # noqa: E402

ABBREV = {
    'App Services Public': 'App Svcs Pub',
    'App Services Admin': 'App Svcs Admin',
    'Capella Mgmt': 'Capella Mgmt',
    'Sync GW Public': 'Sync GW Pub',
    'Sync GW Admin': 'Sync GW Admin',
}

LINES = [
    {
        "name": 'Server Services',
        "color": '#EA2328',
        "stations": [
        ('Server', (270, 200)),
        ('Query', (440, 175)),
        ('Analytics', (610, 165)),
        ('Search', (780, 175)),
        ('Eventing', (950, 200)),
        ],
    },
    {
        "name": 'Management & Sync',
        "color": '#1E5BD0',
        "stations": [
        ('Backup', (270, 320)),
        ('XDCR', (440, 295)),
        ('Capella Mgmt', (610, 295)),
        ],
    },
    {
        "name": 'App Services',
        "color": '#5A6275',
        "closed": True,
        "stations": [
        ('App Services Public', (810, 470)),
        ('App Services Admin', (920, 560)),
        ('Sync GW Public', (810, 660)),
        ('Sync GW Admin', (700, 560)),
        ],
    },
]

URL_OVERRIDES = {
    'Server': 'https://apis.apis.io/apis/couchbase/couchbase-server-rest-api/',
    'Query': 'https://apis.apis.io/apis/couchbase/couchbase-query-service-rest-api/',
    'Analytics': 'https://apis.apis.io/apis/couchbase/couchbase-analytics-service-rest-api/',
    'Search': 'https://apis.apis.io/apis/couchbase/couchbase-search-service-rest-api/',
    'Eventing': 'https://apis.apis.io/apis/couchbase/couchbase-eventing-service-rest-api/',
    'Backup': 'https://apis.apis.io/apis/couchbase/couchbase-backup-service-rest-api/',
    'XDCR': 'https://apis.apis.io/apis/couchbase/couchbase-xdcr-rest-api/',
    'Capella Mgmt': 'https://apis.apis.io/apis/couchbase/couchbase-capella-management-api/',
    'App Services Public': 'https://apis.apis.io/apis/couchbase/couchbase-capella-app-services-public-api/',
    'App Services Admin': 'https://apis.apis.io/apis/couchbase/couchbase-capella-app-services-admin-api/',
    'Sync GW Public': 'https://apis.apis.io/apis/couchbase/couchbase-sync-gateway-public-rest-api/',
    'Sync GW Admin': 'https://apis.apis.io/apis/couchbase/couchbase-sync-gateway-admin-rest-api/',
}


def main():
    seen = set()
    n_unique = 0
    for ln in LINES:
        for (st, _) in ln["stations"]:
            if st not in seen:
                n_unique += 1
                seen.add(st)
    build_subway(
        title='The Couchbase API · Underground Map',
        subtitle=f"{n_unique} APIs · {len(LINES)} functional lines · click any station for the apis.io page",
        lines=LINES,
        abbrev=ABBREV,
        source_label='Source: couchbase/openapi · github.com/api-evangelist/couchbase',
        out_dir=Path(__file__).resolve().parent,
        out_basename='couchbase-subway-map',
        provider_id='couchbase',
        station_url_overrides=URL_OVERRIDES,
    )


if __name__ == "__main__":
    main()
